apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-kafka-producer
  template:
    metadata:
      labels:
        app: reactive-kafka-producer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: reactive-kafka-producer
        image: mmgithubacr.azurecr.io/reactive-kafka-producer:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: reactive-kafka-producer-svc
spec:
  ports:
  - port: 8081
  selector:
    app: reactive-kafka-producer