name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and push image
      id: build-image
      run: |
        az acr build --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/reactive-kafka-producer:${{ github.sha }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --build-arg account_name=${{secrets.ACCOUNT_NAME}} --build-arg cluster_api_key=${{secrets.CLUSTER_API_KEY}} --build-arg cluster_api_secret=${{secrets.CLUSTER_API_SECRET}} --build-arg sr_api_key=${{secrets.SR_API_KEY}} --build-arg sr_api_secret=${{secrets.SR_API_SECRET}} --build-arg sr_url=${{secrets.SR_URL}} --build-arg container_name=${{secrets.CONTAINER_NAME}} --build-arg connection_string=${{secrets.CONNECTION_STRING}} --file "Dockerfile" .